language:
    csharp

install:
    - nuget restore cybersource-rest-samples-csharp.sln
    
script:
    - xbuild ./src/SampleCode.csproj
    - chmod a+x ./src/SampleCode.exe
    - ./src/SampleCode.exe RunAll