os: windows
language: cpp
env:
  - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
before:
  - export PATH=$MSBUILD_PATH:$PATH

install:
    - nuget restore cybersource-rest-samples-csharp.sln
    
script:
    - msbuild /p:Configuration=Release cybersource-rest-samples-csharp.sln
    - dir
